[tools]
node = "24"

[tasks."astro:dev"]
description = "Start the development server"
run = "pnpm dev"
[tasks."astro:build"]
confirm = "Are you sure you want to build the project?"
description = "Build the project"
run = "pnpm build"
[tasks."astro:preview"]
description = "Preview the build"
run = "pnpm preview"
depends = ["astro:build"]

[tasks."astro:upgrade"]
description = "Upgrade Astro to the latest version"
run = "pnpx @astrojs/upgrade"
[tasks."astro:check"]
description = "Run astro check"
run = "pnpm check"

[tasks."biome:format"]
confirm = "Are you sure you want to format the code?"
description = "Format the codebase using Biome"
run = "pnpm format ./src"
[tasks."biome:lint"]
confirm = "Are you sure you want to lint the code?"
description = "Lint the codebase using Biome"
run = "pnpm lint ./src"
